name: ae_pet
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  stream_bloc: ^0.5.2
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.0

  go_router: ^5.1.0

  collection: ^1.16.0
  meta: ^1.8.0

  pure: ^0.2.0
  # sum: ^0.2.0

  freezed_annotation: ^2.2.0

  pinput: ^2.2.16

  # log
  l: 3.2.0
  stack_trace: 1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # test: ^1.21.6
  bloc_test: ^9.1.0
  mockito: ^5.3.2

  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.13.0
  purple_metrics_lints: ^0.3.0

  build_runner: ^2.2.1
  freezed: ^2.2.0
  
flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
